### ISSUE TITLE
SAMix PDFT Error (Single State)

### ISSUE THREAD

**Issue by rebeccadanto** [pyscf/pyscf-forge#29]
Getting the following error when running mcpdft on a single root: 
<pre><code>Traceback (most recent call last):
  File "/home/rdanto/.local/lib/python3.8/site-packages/pyscf/mcscf/addons.py", line 1188, in __getitem__
    return self._data[key]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "new_script.py", line 101, in <module>
    mc.kernel()
  File "/home/rdanto/apps/pyscf_ext/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 488, in kernel
    self.compute_pdft_energy_(otxc=otxc, grids_attr=grids_attr,
  File "/home/rdanto/apps/pyscf_ext/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 482, in compute_pdft_energy_
    self.e_tot, self.e_ot = self.energy_tot (mo_coeff=self.mo_coeff, ci=self.ci)
  File "/home/rdanto/apps/pyscf_ext/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 680, in energy_tot
    e_tot, e_ot = energy_tot (self, mo_coeff=mo_coeff, ot=ot, ci=ci,
  File "/home/rdanto/apps/pyscf_ext/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 72, in energy_tot
    casdm1s = mc.make_one_casdm1s (ci, state=state)
  File "/home/rdanto/apps/pyscf_ext/pyscf-forge/pyscf/mcpdft/_dms.py", line 76, in make_one_casdm1s
    return fcisolver.make_rdm1s (ci, ncas, nelecas)
  File "/home/rdanto/.local/lib/python3.8/site-packages/pyscf/mcscf/addons.py", line 1360, in make_rdm1s
    dm1a, dm1b = self.states_make_rdm1s (ci0, norb, nelec, link_index=link_index, **kwargs)
  File "/home/rdanto/.local/lib/python3.8/site-packages/pyscf/mcscf/addons.py", line 1354, in states_make_rdm1s
    for dm1s in self._collect ('make_rdm1s', ci0, norb, nelec, link_index=link_index, **kwargs):
  File "/home/rdanto/.local/lib/python3.8/site-packages/pyscf/mcscf/addons.py", line 1286, in _collect
    for solver, args, kwargs in self._loop_civecs(*args, **kwargs):
  File "/home/rdanto/.local/lib/python3.8/site-packages/pyscf/mcscf/addons.py", line 1260, in _loop_civecs
    my_args.append (arg[j])
  File "/home/rdanto/.local/lib/python3.8/site-packages/pyscf/mcscf/addons.py", line 1190, in __getitem__
    assert (self._data is None), e
AssertionError: 'int' object is not subscriptable
</code></pre>

**Comment by dking072** [comment]
In the current fork (https://github.com/MatthewRHermes/pyscf-forge/tree/samix_dmrgpdft), e_states returns [None] with only one root in SAmix

**Comment by MatthewRHermes** [comment]
Yes it's a matter of opinion but I agree with @dking072's opinion here; users shouldn't have to figure out the different conditional branches of "in this case it's a list, in this other case it has this other name, in this other case...." `e_states` exists in the first place because `e_tot` is either the state-averaged energy or a list of all state energies depending on its class, and at any rate `[None]` is a nonsensical value for anything to have.

**Comment by MatthewRHermes** [comment]
@rebeccadanto, @dking072, is this fixed now?

**Comment by rebeccadanto** [comment]
Yes, this resolved the issue. Thanks
