### ISSUE TITLE
AssertionError when running with DMRGCASSCF (block)

### ISSUE THREAD

**Issue by HehnLukas** [pyscf/pyscf-forge#9]
When I try to run compute_pdft_energy with a dmrgscf.DMRGCI object as the fcisolver, the make_rdm1s function fails: 

This works with regular casscf and casci. Is this just simply not supported anymore? I remember with an older version (I think published back then on the MRH github), I was able to use dmrg with mcpdft
```
File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/fci/rdm.py", line 104, in make_rdm1_spin1
assert(cibra.size == na*nb)
AssertionError
```

**Comment by MatthewRHermes** [comment]
Could you post more of the traceback and input? I might have inadvertently broken DMRG support when trying to get state-average and state-average mix to work transparently.

**Comment by HehnLukas** [comment]
Sure, here is a minimal example:

```
from pyscf import gto, scf, mcpdft
from pyscf import dmrgscf

mol = gto.M (
    atom = 'O 0 0 0; O 0 0 1.2',
    basis = 'ccpvdz',
    spin = 2)

mf = scf.RHF (mol).run ()

ncas = 6
nelec = 6

mc = dmrgscf.DMRGSCF(mf, ncas, nelec)
mc.fcisolver = dmrgscf.DMRGCI(mol, maxM = 50)
xc = "ftPBE"
cas = mcpdft.CASSCF(mc, 'tPBE', ncas, nelec)
E = cas.compute_pdft_energy_(otxc=xc)
```

Output:

```
converged SCF energy = -149.609461121646
Traceback (most recent call last):
  File "/gpfs/backup/users/home/hehnl/maniqu_nobackup/pyscf/mrsub_test/quick_test_o2/copy/copy/np_mrsub/./test.py", line 18, in <module>
    E = cas.compute_pdft_energy_(otxc=xc)
  File "/gpfs/backup/users/home/hehnl/software/mrh/1.0/pyscf/mcpdft/mcpdft.py", line 480, in compute_pdft_energy_
    self.e_tot, self.e_ot = self.energy_tot (mo_coeff=self.mo_coeff, ci=self.ci)
  File "/gpfs/backup/users/home/hehnl/software/mrh/1.0/pyscf/mcpdft/mcpdft.py", line 664, in energy_tot
    state=state, verbose=verbose)
  File "/gpfs/backup/users/home/hehnl/software/mrh/1.0/pyscf/mcpdft/mcpdft.py", line 72, in energy_tot
    casdm1s = mc.make_one_casdm1s (ci, state=state)
  File "/gpfs/backup/users/home/hehnl/software/mrh/1.0/pyscf/mcpdft/_dms.py", line 64, in make_one_casdm1s
    return fcisolver.make_rdm1s (ci, ncas, nelecas)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/fci/direct_spin1.py", line 799, in make_rdm1s
    return make_rdm1s(fcivec, norb, nelec, link_index)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/fci/direct_spin1.py", line 301, in make_rdm1s
    norb, nelec, link_index)
  File "/software/app/pyscf.org/pyscf/2.0.1/rt_gcc_openmpi/7.2.0-3.0.0/intelpython3.6-2019.1/lib/python3.6/site-packages/pyscf/fci/rdm.py", line 92, in make_rdm1_spin1
    assert(cibra is not None and ciket is not None)
AssertionError
```

This is not the most up to date version from pyscf forge, I had some installation problems with that, rather it is from https://github.com/MatthewRHermes/mcpdft. But I checked the mcpdft.py and _dms.py and it seems like the code is identical

**Comment by MatthewRHermes** [comment]
So in your MWE the `mc.fcisolver` doesn't get patched over to `cas.fcisolver` automatically, but you can just add a line `cas.fcisolver = mc.fcisolver` before `compute_pdft_energy` to do that. Also, you obviously need to actually run the DMRG calculation before computing the MC-PDFT energy. If you make those two changes, then [the branch](https://github.com/MatthewRHermes/pyscf-forge/tree/issue_9) I just created on my fork should work for you. Can you test it? (I haven't made a pull request yet because I'm not sure this works for multiple states.)

**Comment by HehnLukas** [comment]
Thanks for the response. It is not really possible for me to test your commit right now because I'm not able to install the newest version (I will make an issue about that as well), but I did make the changes you suggested. This leads to the error changing, the problem is now in the 2-RDM:

(I also made the changes in your commit manually in the version that is installed for me. However, the result stays the same regardless of whether I do that.)

```
converged SCF energy = -149.609461121647
CASSCF energy = -149.681890704871
CASCI E = -149.681890704871  E(CI) = -12.0541122433456  S^2 = 2.0000000
Traceback (most recent call last):
  File "/gpfs/backup/users/home/hehnl/maniqu_nobackup/pyscf/mrsub_test/quick_test_o2/copy/copy/np_mrsub/./test.py", line 20, in <module>
    E = cas.compute_pdft_energy_(otxc=xc)
  File "/gpfs/backup/users/home/hehnl/software/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 480, in compute_pdft_energy_
    self.e_tot, self.e_ot = self.energy_tot (mo_coeff=self.mo_coeff, ci=self.ci)
  File "/gpfs/backup/users/home/hehnl/software/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 664, in energy_tot
    state=state, verbose=verbose)
  File "/gpfs/backup/users/home/hehnl/software/pyscf-forge/pyscf/mcpdft/mcpdft.py", line 73, in energy_tot
    casdm2 = mc.make_one_casdm2 (ci, state=state)
  File "/gpfs/backup/users/home/hehnl/software/pyscf-forge/pyscf/mcpdft/_dms.py", line 76, in make_one_casdm2
    return fcisolver.make_rdm2 (ci, ncas, nelecas)
AttributeError: 'DMRGCI' object has no attribute 'make_rdm2'

```

**Comment by MatthewRHermes** [comment]
Weird, I wonder why that didn't happen when my colleague tested it here.

This should be an easy fix, but it'll take a bit for me to actually test it because I'm having a bear of a time getting Block compiled. Anyway the code to fix it should be trivial so I pushed it to the issue_9 branch on my fork.

**Comment by HehnLukas** [comment]
So the fix seems to work for me, again with the caveat that I did not manage to install your fork, but rather copied your changes into my older install. Thank you!
